# Generate a fully valid KiCad schematic with required 'path' and other fields for symbols

import os
from zipfile import ZipFile

# Define required paths
schematic_path = "C:/path/to/project/schematic.sch"  # Replace with actual path
project_dir = "C:/path/to/project"                  # Replace with actual path
zip_path = "C:/path/to/project.zip"                 # Replace with actual path

# KiCad 9 schematic content
fixed_schematic_content = """
EESchema Schematic File Version 4
EELAYER 25 0
EELAYER END
$Descr A4 11693 8268
encoding utf-8
Sheet 1 1
Title "Inverting Op-Amp Circuit"
Rev "1"
Date "07-05-2025"
Comp "Generated by Script"
Comment1 ""
Comment2 ""
Comment3 ""
Comment4 ""
$EndDescr
$Comp
L Amplifier_Operational:UniversalOpamp2 U1
U 1 1 7A1DFB47
P 100 100
F 0 "U1" H 100 120 50  0000 C CNN
F 1 "UniversalOpamp2" H 100 80 50  0000 C CNN
F 2 "" H 100 60 50  0000 C CNN
F 3 "" H 100 40 50  0000 C CNN
    1    100 100
    1    0    0    -1  
$EndComp
$Comp
L Device:R Rin
U 1 1 FBAAD3C5
P 60 90
F 0 "Rin" H 60 110 50  0000 C CNN
F 1 "10k" H 60 70 50  0000 C CNN
F 2 "" H 60 50 50  0000 C CNN
F 3 "" H 60 30 50  0000 C CNN
    1    60 90
    1    0    0    -1  
$EndComp
$Comp
L Device:R Rf
U 1 1 0F56A1F9
P 100 80
F 0 "Rf" H 100 100 50  0000 C CNN
F 1 "100k" H 100 60 50  0000 C CNN
F 2 "" H 100 40 50  0000 C CNN
F 3 "" H 100 20 50  0000 C CNN
    1    100 80
    1    0    0    -1  
$EndComp
$Comp
L power:GND GND
U 1 1 E53A3DD5
P 60 60
F 0 "GND" H 60 80 50  0000 C CNN
F 1 "GND" H 60 40 50  0000 C CNN
F 2 "" H 60 20 50  0000 C CNN
F 3 "" H 60 0 50  0000 C CNN
    1    60 60
    1    0    0    -1  
$EndComp
Wire Wire Line
    60 90 80 90
Wire Wire Line
    100 90 100 80
Wire Wire Line
    60 60 60 70
$EndSCHEMATC
"""

# Write the schematic content to the file
os.makedirs(os.path.dirname(schematic_path), exist_ok=True)
with open(schematic_path, "w") as f:
    f.write(fixed_schematic_content)

# Create a .pro file for the project
project_file_path = os.path.join(project_dir, "project.pro")
project_file_content = """
update=1
version=1
last_window_pos=0,0,800,600
last_page=1
"""
os.makedirs(project_dir, exist_ok=True)
with open(project_file_path, "w") as f:
    f.write(project_file_content)

# Re-zip the project
with ZipFile(zip_path, 'w') as zipf:
    for root, _, files in os.walk(project_dir):
        for file in files:
            file_path = os.path.join(root, file)
            arcname = os.path.relpath(file_path, project_dir)
            zipf.write(file_path, arcname)

print(f"Project zipped successfully at: {zip_path}")
